services:
  app:
    build: .
    environment:
      - BASE_URL=https://lorem.video
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    networks:
      - web

  caddy:
    image: ghcr.io/serfriz/caddy-crowdsec:latest
    depends_on:
      crowdsec:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
      - CROWDSEC_API_URL=${CROWDSEC_API_URL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy # Shared logs for CrowdSec to read
    restart: unless-stopped
    networks:
      - web

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    environment:
      - COLLECTIONS=crowdsecurity/caddy crowdsecurity/base-http-scenarios crowdsecurity/whitelist-good-actors
    volumes:
      - caddy_logs:/var/log/caddy:ro         # Read-only access to Caddy logs
      - crowdsec_data:/var/lib/crowdsec/data
      - crowdsec_config:/etc/crowdsec
    restart: unless-stopped
    networks:
      - web

networks:
  web:

volumes:
  caddy_data:
  caddy_config:
  caddy_logs:
  crowdsec_data:
  crowdsec_config: